version: '3.4'

networks:
  c4s.report:

services:
  db: 
    container_name: db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - 8001:1433
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=Wezed!ddwx1
    networks:
        - c4s.report
  api:
    container_name: api
    image: ${DOCKER_REGISTRY-}c4sapi
    build:
      context: .
      dockerfile: C4S.API/Dockerfile
    ports:
        - 8080:8080
    depends_on: 
        - db
    networks:
        - c4s.report
  front:
    container_name: front
    image: front
    build:
        context: ../c4s-report-front/s4c-report-front
        dockerfile: Dockerfile
